#3 Implement IPython REPL
open-craft-guild/blueberrypy pull request #7
Opened 2017-05-09 16:09 UTC by anxolerd

Added blueberrypy ishell command

2017-05-09 20:26 UTC, anxolerd commented
It seems IPython 6.0.0 is not available for Python2.7 Do you plan to support Python2 ?
If no, should I downgrade IPython to lower version?

2017-05-10 07:10 UTC, webknjaz requested changes

2017-05-10 07:10 UTC, webknjaz commented on src/blueberrypy/command.py
> +        elif command == "ishell":
I'd go for extending existing command with autonegotiation of REPL, available for use. See django-extensions - > shell_plus

2017-05-10 07:10 UTC, webknjaz commented on setup.py
> +                    # IPython dependencies:
Why would you need to lock recursive deps?

2017-05-10 07:11 UTC, webknjaz commented
> should I downgrade

There's environment markers for this purpose

2017-05-10 20:34 UTC, anxolerd commented on setup.py
> +                    # IPython dependencies:
Because I do not need any surprises of unexpected updates.
Do you think I should not do that and lock only IPython dependency?

2017-05-11 07:47 UTC, webknjaz commented on setup.py
> +                    # IPython dependencies:
In a project of a library type you shouldn't restrict versioning strictly unless for corner cases.

2017-05-11 07:52 UTC, webknjaz requested changes
plz also move ipython to extras

2017-05-11 07:52 UTC, webknjaz commented on setup.py
> +                    else "ipython==6.0.0"]
`>=`

2017-05-11 07:52 UTC, webknjaz commented on setup.py
> +                    "ipython==5.3.0" if sys.version_info < (3, 3)
`<=`

2017-05-11 07:52 UTC, webknjaz commented on src/blueberrypy/command.py
> +from IPython.terminal.interactiveshell import TerminalInteractiveShell
this will fail if ipython isn't installed

2017-05-11 07:53 UTC, webknjaz commented
can you borrow the whole logic from django-extensions?

2017-05-11 07:55 UTC, anxolerd commented on setup.py
> +                    # IPython dependencies:
Well, I do not trust them enough to do that.

But if you wish I may fix that if you tell me which versions should I allow.

2017-05-11 07:56 UTC, anxolerd commented on src/blueberrypy/command.py
> +from IPython.terminal.interactiveshell import TerminalInteractiveShell
Ipython is in core dependencies so I guess it will be installed with the blueberrypy

2017-05-11 07:56 UTC, anxolerd commented
> can you borrow the whole logic from django-extensions?

What do you mean by that?

2017-05-11 07:57 UTC, webknjaz commented on src/blueberrypy/command.py
> +from IPython.terminal.interactiveshell import TerminalInteractiveShell
and it shouldn't be there

2017-05-11 07:58 UTC, webknjaz commented
copy-paste driven development, I think

2017-05-11 07:58 UTC, webknjaz commented on setup.py
> +                    # IPython dependencies:
see below

2017-05-11 08:01 UTC, anxolerd commented on src/blueberrypy/command.py
> +from IPython.terminal.interactiveshell import TerminalInteractiveShell
Why shouldn't it?

2017-05-11 08:03 UTC, anxolerd commented
> copy-paste driven development, I think
I do not understand what exactly you want me to copy-paste. Other shells support? Or what?

2017-05-11 08:11 UTC, webknjaz commented on src/blueberrypy/command.py
> +from IPython.terminal.interactiveshell import TerminalInteractiveShell
because it's not a runtime dependency, it should be optional; if one wants to use ipython they'll install it.

2017-06-20 21:15 UTC, anxolerd commented
Updated PR. @webknjaz pls review again =)

2017-06-22 04:59 UTC, webknjaz requested changes
So what about other shells?

2017-06-22 04:59 UTC, webknjaz commented on setup.py
> +                              "ipython<=5.3.0" if sys.version_info < (3, 3) else "ipython>=6.0.0"],
This conditional must be computed once and passed via variable; alternatively, you may wrap it into lambda. Copy-pasted code snippets lead to unexpected diversity increase of code base over time.

2017-06-22 04:59 UTC, webknjaz commented on src/blueberrypy/command.py
> +import blueberrypy.shell as shell
Isn't `from blueberrypy import shell` shorter?

2017-06-22 04:59 UTC, webknjaz commented on src/blueberrypy/shell.py
> +    return (
`getattr(config, 'project_metadata', {}).get('package', None)`

2017-06-22 04:59 UTC, webknjaz commented on src/blueberrypy/shell.py
> +def _make_sa_engine(config):
Can't this code be shared with SQLAlchemy Tool module?

2017-06-25 14:31 UTC, anxolerd commented on src/blueberrypy/shell.py
> +def _make_sa_engine(config):
No it cannot be shared properly =(

2017-06-25 14:32 UTC, anxolerd commented on src/blueberrypy/shell.py
> +    return (
I think my version is more explicit.

2017-06-25 14:32 UTC, anxolerd commented on src/blueberrypy/command.py
> +import blueberrypy.shell as shell
Yes, it is.

2017-06-25 14:32 UTC, anxolerd commented on setup.py
> +                              "ipython<=5.3.0" if sys.version_info < (3, 3) else "ipython>=6.0.0"],
Agree

2017-06-25 14:33 UTC, anxolerd commented
I think we'll stop on IPython for now. Will add other shells on demand.

2017-06-25 14:35 UTC, anxolerd commented
@webknjaz:
- removed code duplication from setup.py
- shorter import is used

I do not see any good way to share code with SQLAlchemy tool without overcomplicating the tool itself.

2017-06-25 16:46 UTC, webknjaz commented on src/blueberrypy/shell.py
> +    if config.use_sqlalchemy:
I think you could reuse this property https://github.com/open-craft-guild/blueberrypy/blob/master/src/blueberrypy/config.py#L270

2017-06-25 16:58 UTC, webknjaz commented on src/blueberrypy/shell.py
> +    assert isinstance(config, BlueberryPyConfiguration), type(config)
`type(config)` doesn't look like sufficient error message

2017-06-25 17:51 UTC, anxolerd commented on src/blueberrypy/shell.py
> +    if config.use_sqlalchemy:
The logic I used was present in old blueberrypy console. This is why I kept it.

2017-06-25 17:52 UTC, anxolerd commented on src/blueberrypy/shell.py
> +    assert isinstance(config, BlueberryPyConfiguration), type(config)
Agree. Fixed in 44e80e3

2017-06-26 09:54 UTC, webknjaz approved these changes

2017-06-26 14:30 UTC, anxolerd commented
May I merge?

2017-06-26 14:30 UTC, anxolerd commented
@webknjaz can this be merged, or any further changes are required?

2017-06-26 14:31 UTC, webknjaz commented
Go ahead and merge it.

On Jun 26, 2017 17:30, "Oleksandr Kovalchuk" <notifications@github.com>
wrote:

> @webknjaz <https://github.com/webknjaz> can this be merged, or any
> further changes are required?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/open-craft-guild/blueberrypy/pull/7#issuecomment-311076551>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAjT71JfY9JgNkqslyOIbtp93ysjmMU4ks5sH8CYgaJpZM4NVipO>
> .
>

2017-06-26 14:39 UTC, anxolerd commented
@webknjaz I am not authorized to merge this pull request.

2017-06-26 19:56 UTC, webknjaz commented
> This branch is out of sync with the base branch.
Changes from the base branch must be synced with this branch before merging.

Fix this first

2017-06-28 12:20 UTC, closed without merging